#!/bin/bash

a=$(du /etc/)
nr_files=$(du /etc/ | wc -l )


soma=0

for i in $a
do 
    if echo $i | grep -q '^[0-9]\+$'; then
        # Soma o valor numérico à variável soma
        ((soma += i))
    fi
done

# usamos o let para fazer um conta aritmetica e nao uma concatenacao de strings
let media=$soma/$nr_files

echo "Numero total ficheiros: $nr_files"
echo "soma total: $soma"
echo "media: $media"

maior_ficheiro=$(du /etc/ | sort -g | awk '{print $1}'  | tail -n 1)
menor_ficheiro=$(du /etc/ | sort -g | awk '{print $1}'  | head -n 1)


echo "maior ficheiro: $maior_ficheiro"
echo "maior ficheiro: $menor_ficheiro"